# Generated by Django 6.0.1 on 2026-01-25 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedUniversityCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'approved_university_credentials',
                'ordering': ['-approved_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovedUniversityAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('university_email', models.EmailField(max_length=254, unique=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=20)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True, max_length=500, null=True)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='university_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Approved University',
                'verbose_name_plural': 'Approved Universities',
                'ordering': ['-approved_at'],
            },
        ),
    ]
