# Generated by Django 6.0.1 on 2026-01-25 15:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_id', models.CharField(max_length=50, unique=True, verbose_name='College ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('university_email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=20)),
                ('website', models.URLField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
