# Generated by Django 6.0.1 on 2026-02-01 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_login_valid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AISHE_Code', models.CharField(max_length=50)),
                ('College_name', models.CharField(max_length=255)),
                ('StudentID', models.CharField(max_length=100, unique=True)),
                ('student_password', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
